language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jrudd/docker-react -f Dockerfile.dev .

script:
  - docker run jrudd/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react1"
  env: "Dockerreact1-env"
  bucker_name: "elasticbeanstalk-us-east-2-670901130033"
  bucket_path: "docker-react1"
  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY